/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSetupProfileRouteImport } from './routes/app/setup-profile'
import { Route as AppAuthedRouteImport } from './routes/app/_authed'
import { Route as AppAuthedIndexRouteImport } from './routes/app/_authed/index'
import { Route as AppAuthedMySessionsRouteImport } from './routes/app/_authed/my-sessions'
import { Route as AppAuthedLeaderboardRouteImport } from './routes/app/_authed/leaderboard'
import { Route as AppAuthedAdminRouteImport } from './routes/app/_authed/admin'
import { Route as AppAuthedAdminIndexRouteImport } from './routes/app/_authed/admin/index'
import { Route as AppAuthedAdminMembersRouteImport } from './routes/app/_authed/admin/members'
import { Route as AppAuthedAdminLogSessionRouteImport } from './routes/app/_authed/admin/log-session'
import { Route as AppAuthedAdminImportRouteImport } from './routes/app/_authed/admin/import'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSetupProfileRoute = AppSetupProfileRouteImport.update({
  id: '/app/setup-profile',
  path: '/app/setup-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedRoute = AppAuthedRouteImport.update({
  id: '/app/_authed',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedIndexRoute = AppAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedMySessionsRoute = AppAuthedMySessionsRouteImport.update({
  id: '/my-sessions',
  path: '/my-sessions',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedLeaderboardRoute = AppAuthedLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedAdminRoute = AppAuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedAdminIndexRoute = AppAuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedAdminRoute,
} as any)
const AppAuthedAdminMembersRoute = AppAuthedAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppAuthedAdminRoute,
} as any)
const AppAuthedAdminLogSessionRoute =
  AppAuthedAdminLogSessionRouteImport.update({
    id: '/log-session',
    path: '/log-session',
    getParentRoute: () => AppAuthedAdminRoute,
  } as any)
const AppAuthedAdminImportRoute = AppAuthedAdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppAuthedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAuthedRouteWithChildren
  '/app/setup-profile': typeof AppSetupProfileRoute
  '/app/admin': typeof AppAuthedAdminRouteWithChildren
  '/app/leaderboard': typeof AppAuthedLeaderboardRoute
  '/app/my-sessions': typeof AppAuthedMySessionsRoute
  '/app/': typeof AppAuthedIndexRoute
  '/app/admin/import': typeof AppAuthedAdminImportRoute
  '/app/admin/log-session': typeof AppAuthedAdminLogSessionRoute
  '/app/admin/members': typeof AppAuthedAdminMembersRoute
  '/app/admin/': typeof AppAuthedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/setup-profile': typeof AppSetupProfileRoute
  '/app/leaderboard': typeof AppAuthedLeaderboardRoute
  '/app/my-sessions': typeof AppAuthedMySessionsRoute
  '/app': typeof AppAuthedIndexRoute
  '/app/admin/import': typeof AppAuthedAdminImportRoute
  '/app/admin/log-session': typeof AppAuthedAdminLogSessionRoute
  '/app/admin/members': typeof AppAuthedAdminMembersRoute
  '/app/admin': typeof AppAuthedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/_authed': typeof AppAuthedRouteWithChildren
  '/app/setup-profile': typeof AppSetupProfileRoute
  '/app/_authed/admin': typeof AppAuthedAdminRouteWithChildren
  '/app/_authed/leaderboard': typeof AppAuthedLeaderboardRoute
  '/app/_authed/my-sessions': typeof AppAuthedMySessionsRoute
  '/app/_authed/': typeof AppAuthedIndexRoute
  '/app/_authed/admin/import': typeof AppAuthedAdminImportRoute
  '/app/_authed/admin/log-session': typeof AppAuthedAdminLogSessionRoute
  '/app/_authed/admin/members': typeof AppAuthedAdminMembersRoute
  '/app/_authed/admin/': typeof AppAuthedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/setup-profile'
    | '/app/admin'
    | '/app/leaderboard'
    | '/app/my-sessions'
    | '/app/'
    | '/app/admin/import'
    | '/app/admin/log-session'
    | '/app/admin/members'
    | '/app/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/setup-profile'
    | '/app/leaderboard'
    | '/app/my-sessions'
    | '/app'
    | '/app/admin/import'
    | '/app/admin/log-session'
    | '/app/admin/members'
    | '/app/admin'
  id:
    | '__root__'
    | '/'
    | '/app/_authed'
    | '/app/setup-profile'
    | '/app/_authed/admin'
    | '/app/_authed/leaderboard'
    | '/app/_authed/my-sessions'
    | '/app/_authed/'
    | '/app/_authed/admin/import'
    | '/app/_authed/admin/log-session'
    | '/app/_authed/admin/members'
    | '/app/_authed/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppAuthedRoute: typeof AppAuthedRouteWithChildren
  AppSetupProfileRoute: typeof AppSetupProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/setup-profile': {
      id: '/app/setup-profile'
      path: '/app/setup-profile'
      fullPath: '/app/setup-profile'
      preLoaderRoute: typeof AppSetupProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authed': {
      id: '/app/_authed'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authed/': {
      id: '/app/_authed/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthedIndexRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/my-sessions': {
      id: '/app/_authed/my-sessions'
      path: '/my-sessions'
      fullPath: '/app/my-sessions'
      preLoaderRoute: typeof AppAuthedMySessionsRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/leaderboard': {
      id: '/app/_authed/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppAuthedLeaderboardRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/admin': {
      id: '/app/_authed/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAuthedAdminRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/admin/': {
      id: '/app/_authed/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAuthedAdminIndexRouteImport
      parentRoute: typeof AppAuthedAdminRoute
    }
    '/app/_authed/admin/members': {
      id: '/app/_authed/admin/members'
      path: '/members'
      fullPath: '/app/admin/members'
      preLoaderRoute: typeof AppAuthedAdminMembersRouteImport
      parentRoute: typeof AppAuthedAdminRoute
    }
    '/app/_authed/admin/log-session': {
      id: '/app/_authed/admin/log-session'
      path: '/log-session'
      fullPath: '/app/admin/log-session'
      preLoaderRoute: typeof AppAuthedAdminLogSessionRouteImport
      parentRoute: typeof AppAuthedAdminRoute
    }
    '/app/_authed/admin/import': {
      id: '/app/_authed/admin/import'
      path: '/import'
      fullPath: '/app/admin/import'
      preLoaderRoute: typeof AppAuthedAdminImportRouteImport
      parentRoute: typeof AppAuthedAdminRoute
    }
  }
}

interface AppAuthedAdminRouteChildren {
  AppAuthedAdminImportRoute: typeof AppAuthedAdminImportRoute
  AppAuthedAdminLogSessionRoute: typeof AppAuthedAdminLogSessionRoute
  AppAuthedAdminMembersRoute: typeof AppAuthedAdminMembersRoute
  AppAuthedAdminIndexRoute: typeof AppAuthedAdminIndexRoute
}

const AppAuthedAdminRouteChildren: AppAuthedAdminRouteChildren = {
  AppAuthedAdminImportRoute: AppAuthedAdminImportRoute,
  AppAuthedAdminLogSessionRoute: AppAuthedAdminLogSessionRoute,
  AppAuthedAdminMembersRoute: AppAuthedAdminMembersRoute,
  AppAuthedAdminIndexRoute: AppAuthedAdminIndexRoute,
}

const AppAuthedAdminRouteWithChildren = AppAuthedAdminRoute._addFileChildren(
  AppAuthedAdminRouteChildren,
)

interface AppAuthedRouteChildren {
  AppAuthedAdminRoute: typeof AppAuthedAdminRouteWithChildren
  AppAuthedLeaderboardRoute: typeof AppAuthedLeaderboardRoute
  AppAuthedMySessionsRoute: typeof AppAuthedMySessionsRoute
  AppAuthedIndexRoute: typeof AppAuthedIndexRoute
}

const AppAuthedRouteChildren: AppAuthedRouteChildren = {
  AppAuthedAdminRoute: AppAuthedAdminRouteWithChildren,
  AppAuthedLeaderboardRoute: AppAuthedLeaderboardRoute,
  AppAuthedMySessionsRoute: AppAuthedMySessionsRoute,
  AppAuthedIndexRoute: AppAuthedIndexRoute,
}

const AppAuthedRouteWithChildren = AppAuthedRoute._addFileChildren(
  AppAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppAuthedRoute: AppAuthedRouteWithChildren,
  AppSetupProfileRoute: AppSetupProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
