/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSetupProfileRouteImport } from './routes/app/setup-profile'
import { Route as AppPendingRouteImport } from './routes/app/pending'
import { Route as AppAuthedRouteImport } from './routes/app/_authed'
import { Route as AppAuthedIndexRouteImport } from './routes/app/_authed/index'
import { Route as AppAuthedSettingsRouteImport } from './routes/app/_authed/settings'
import { Route as AppAuthedNotesRouteImport } from './routes/app/_authed/notes'
import { Route as AppAuthedMySessionsRouteImport } from './routes/app/_authed/my-sessions'
import { Route as AppAuthedLeaderboardRouteImport } from './routes/app/_authed/leaderboard'
import { Route as AppAuthedAdminRouteImport } from './routes/app/_authed/admin'
import { Route as AppAuthedAdminIndexRouteImport } from './routes/app/_authed/admin/index'
import { Route as AppAuthedAdminMembersRouteImport } from './routes/app/_authed/admin/members'
import { Route as AppAuthedAdminLogSessionRouteImport } from './routes/app/_authed/admin/log-session'
import { Route as AppAuthedAdminInboxRouteImport } from './routes/app/_authed/admin/inbox'
import { Route as AppAuthedAdminImportRouteImport } from './routes/app/_authed/admin/import'
import { Route as AppAuthedAdminClubPlacesRouteImport } from './routes/app/_authed/admin/club-places'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSetupProfileRoute = AppSetupProfileRouteImport.update({
  id: '/app/setup-profile',
  path: '/app/setup-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPendingRoute = AppPendingRouteImport.update({
  id: '/app/pending',
  path: '/app/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedRoute = AppAuthedRouteImport.update({
  id: '/app/_authed',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedIndexRoute = AppAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedSettingsRoute = AppAuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedNotesRoute = AppAuthedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedMySessionsRoute = AppAuthedMySessionsRouteImport.update({
  id: '/my-sessions',
  path: '/my-sessions',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedLeaderboardRoute = AppAuthedLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedAdminRoute = AppAuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedAdminIndexRoute = AppAuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedAdminRoute,
} as any)
const AppAuthedAdminMembersRoute = AppAuthedAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppAuthedAdminRoute,
} as any)
const AppAuthedAdminLogSessionRoute =
  AppAuthedAdminLogSessionRouteImport.update({
    id: '/log-session',
    path: '/log-session',
    getParentRoute: () => AppAuthedAdminRoute,
  } as any)
const AppAuthedAdminInboxRoute = AppAuthedAdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppAuthedAdminRoute,
} as any)
const AppAuthedAdminImportRoute = AppAuthedAdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppAuthedAdminRoute,
} as any)
const AppAuthedAdminClubPlacesRoute =
  AppAuthedAdminClubPlacesRouteImport.update({
    id: '/club-places',
    path: '/club-places',
    getParentRoute: () => AppAuthedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAuthedRouteWithChildren
  '/app/pending': typeof AppPendingRoute
  '/app/setup-profile': typeof AppSetupProfileRoute
  '/app/admin': typeof AppAuthedAdminRouteWithChildren
  '/app/leaderboard': typeof AppAuthedLeaderboardRoute
  '/app/my-sessions': typeof AppAuthedMySessionsRoute
  '/app/notes': typeof AppAuthedNotesRoute
  '/app/settings': typeof AppAuthedSettingsRoute
  '/app/': typeof AppAuthedIndexRoute
  '/app/admin/club-places': typeof AppAuthedAdminClubPlacesRoute
  '/app/admin/import': typeof AppAuthedAdminImportRoute
  '/app/admin/inbox': typeof AppAuthedAdminInboxRoute
  '/app/admin/log-session': typeof AppAuthedAdminLogSessionRoute
  '/app/admin/members': typeof AppAuthedAdminMembersRoute
  '/app/admin/': typeof AppAuthedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/pending': typeof AppPendingRoute
  '/app/setup-profile': typeof AppSetupProfileRoute
  '/app/leaderboard': typeof AppAuthedLeaderboardRoute
  '/app/my-sessions': typeof AppAuthedMySessionsRoute
  '/app/notes': typeof AppAuthedNotesRoute
  '/app/settings': typeof AppAuthedSettingsRoute
  '/app': typeof AppAuthedIndexRoute
  '/app/admin/club-places': typeof AppAuthedAdminClubPlacesRoute
  '/app/admin/import': typeof AppAuthedAdminImportRoute
  '/app/admin/inbox': typeof AppAuthedAdminInboxRoute
  '/app/admin/log-session': typeof AppAuthedAdminLogSessionRoute
  '/app/admin/members': typeof AppAuthedAdminMembersRoute
  '/app/admin': typeof AppAuthedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/_authed': typeof AppAuthedRouteWithChildren
  '/app/pending': typeof AppPendingRoute
  '/app/setup-profile': typeof AppSetupProfileRoute
  '/app/_authed/admin': typeof AppAuthedAdminRouteWithChildren
  '/app/_authed/leaderboard': typeof AppAuthedLeaderboardRoute
  '/app/_authed/my-sessions': typeof AppAuthedMySessionsRoute
  '/app/_authed/notes': typeof AppAuthedNotesRoute
  '/app/_authed/settings': typeof AppAuthedSettingsRoute
  '/app/_authed/': typeof AppAuthedIndexRoute
  '/app/_authed/admin/club-places': typeof AppAuthedAdminClubPlacesRoute
  '/app/_authed/admin/import': typeof AppAuthedAdminImportRoute
  '/app/_authed/admin/inbox': typeof AppAuthedAdminInboxRoute
  '/app/_authed/admin/log-session': typeof AppAuthedAdminLogSessionRoute
  '/app/_authed/admin/members': typeof AppAuthedAdminMembersRoute
  '/app/_authed/admin/': typeof AppAuthedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/pending'
    | '/app/setup-profile'
    | '/app/admin'
    | '/app/leaderboard'
    | '/app/my-sessions'
    | '/app/notes'
    | '/app/settings'
    | '/app/'
    | '/app/admin/club-places'
    | '/app/admin/import'
    | '/app/admin/inbox'
    | '/app/admin/log-session'
    | '/app/admin/members'
    | '/app/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/pending'
    | '/app/setup-profile'
    | '/app/leaderboard'
    | '/app/my-sessions'
    | '/app/notes'
    | '/app/settings'
    | '/app'
    | '/app/admin/club-places'
    | '/app/admin/import'
    | '/app/admin/inbox'
    | '/app/admin/log-session'
    | '/app/admin/members'
    | '/app/admin'
  id:
    | '__root__'
    | '/'
    | '/app/_authed'
    | '/app/pending'
    | '/app/setup-profile'
    | '/app/_authed/admin'
    | '/app/_authed/leaderboard'
    | '/app/_authed/my-sessions'
    | '/app/_authed/notes'
    | '/app/_authed/settings'
    | '/app/_authed/'
    | '/app/_authed/admin/club-places'
    | '/app/_authed/admin/import'
    | '/app/_authed/admin/inbox'
    | '/app/_authed/admin/log-session'
    | '/app/_authed/admin/members'
    | '/app/_authed/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppAuthedRoute: typeof AppAuthedRouteWithChildren
  AppPendingRoute: typeof AppPendingRoute
  AppSetupProfileRoute: typeof AppSetupProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/setup-profile': {
      id: '/app/setup-profile'
      path: '/app/setup-profile'
      fullPath: '/app/setup-profile'
      preLoaderRoute: typeof AppSetupProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pending': {
      id: '/app/pending'
      path: '/app/pending'
      fullPath: '/app/pending'
      preLoaderRoute: typeof AppPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authed': {
      id: '/app/_authed'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authed/': {
      id: '/app/_authed/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthedIndexRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/settings': {
      id: '/app/_authed/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppAuthedSettingsRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/notes': {
      id: '/app/_authed/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppAuthedNotesRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/my-sessions': {
      id: '/app/_authed/my-sessions'
      path: '/my-sessions'
      fullPath: '/app/my-sessions'
      preLoaderRoute: typeof AppAuthedMySessionsRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/leaderboard': {
      id: '/app/_authed/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppAuthedLeaderboardRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/admin': {
      id: '/app/_authed/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAuthedAdminRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/admin/': {
      id: '/app/_authed/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAuthedAdminIndexRouteImport
      parentRoute: typeof AppAuthedAdminRoute
    }
    '/app/_authed/admin/members': {
      id: '/app/_authed/admin/members'
      path: '/members'
      fullPath: '/app/admin/members'
      preLoaderRoute: typeof AppAuthedAdminMembersRouteImport
      parentRoute: typeof AppAuthedAdminRoute
    }
    '/app/_authed/admin/log-session': {
      id: '/app/_authed/admin/log-session'
      path: '/log-session'
      fullPath: '/app/admin/log-session'
      preLoaderRoute: typeof AppAuthedAdminLogSessionRouteImport
      parentRoute: typeof AppAuthedAdminRoute
    }
    '/app/_authed/admin/inbox': {
      id: '/app/_authed/admin/inbox'
      path: '/inbox'
      fullPath: '/app/admin/inbox'
      preLoaderRoute: typeof AppAuthedAdminInboxRouteImport
      parentRoute: typeof AppAuthedAdminRoute
    }
    '/app/_authed/admin/import': {
      id: '/app/_authed/admin/import'
      path: '/import'
      fullPath: '/app/admin/import'
      preLoaderRoute: typeof AppAuthedAdminImportRouteImport
      parentRoute: typeof AppAuthedAdminRoute
    }
    '/app/_authed/admin/club-places': {
      id: '/app/_authed/admin/club-places'
      path: '/club-places'
      fullPath: '/app/admin/club-places'
      preLoaderRoute: typeof AppAuthedAdminClubPlacesRouteImport
      parentRoute: typeof AppAuthedAdminRoute
    }
  }
}

interface AppAuthedAdminRouteChildren {
  AppAuthedAdminClubPlacesRoute: typeof AppAuthedAdminClubPlacesRoute
  AppAuthedAdminImportRoute: typeof AppAuthedAdminImportRoute
  AppAuthedAdminInboxRoute: typeof AppAuthedAdminInboxRoute
  AppAuthedAdminLogSessionRoute: typeof AppAuthedAdminLogSessionRoute
  AppAuthedAdminMembersRoute: typeof AppAuthedAdminMembersRoute
  AppAuthedAdminIndexRoute: typeof AppAuthedAdminIndexRoute
}

const AppAuthedAdminRouteChildren: AppAuthedAdminRouteChildren = {
  AppAuthedAdminClubPlacesRoute: AppAuthedAdminClubPlacesRoute,
  AppAuthedAdminImportRoute: AppAuthedAdminImportRoute,
  AppAuthedAdminInboxRoute: AppAuthedAdminInboxRoute,
  AppAuthedAdminLogSessionRoute: AppAuthedAdminLogSessionRoute,
  AppAuthedAdminMembersRoute: AppAuthedAdminMembersRoute,
  AppAuthedAdminIndexRoute: AppAuthedAdminIndexRoute,
}

const AppAuthedAdminRouteWithChildren = AppAuthedAdminRoute._addFileChildren(
  AppAuthedAdminRouteChildren,
)

interface AppAuthedRouteChildren {
  AppAuthedAdminRoute: typeof AppAuthedAdminRouteWithChildren
  AppAuthedLeaderboardRoute: typeof AppAuthedLeaderboardRoute
  AppAuthedMySessionsRoute: typeof AppAuthedMySessionsRoute
  AppAuthedNotesRoute: typeof AppAuthedNotesRoute
  AppAuthedSettingsRoute: typeof AppAuthedSettingsRoute
  AppAuthedIndexRoute: typeof AppAuthedIndexRoute
}

const AppAuthedRouteChildren: AppAuthedRouteChildren = {
  AppAuthedAdminRoute: AppAuthedAdminRouteWithChildren,
  AppAuthedLeaderboardRoute: AppAuthedLeaderboardRoute,
  AppAuthedMySessionsRoute: AppAuthedMySessionsRoute,
  AppAuthedNotesRoute: AppAuthedNotesRoute,
  AppAuthedSettingsRoute: AppAuthedSettingsRoute,
  AppAuthedIndexRoute: AppAuthedIndexRoute,
}

const AppAuthedRouteWithChildren = AppAuthedRoute._addFileChildren(
  AppAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppAuthedRoute: AppAuthedRouteWithChildren,
  AppPendingRoute: AppPendingRoute,
  AppSetupProfileRoute: AppSetupProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
